version: "3"
services:
  oracle:
    hostname: oracle
    environment:
      - ORACLE_SID=MAXDB761
      - ORACLE_PWD=changepwd123
      - DB_HOST_NAME=oracle
    networks:
      - maxnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure  
    volumes:
      - ~/oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
    image: oracle/database:12.2.0.1-ee
    privileged: true
  maximo:
    image: maximo/maximo:latest
    environment:
      - MXINTADM_PASSWORD=mxintadm
      - MAXADMIN_PASSWORD=maxadmin
      - ORACLE_PWD=changepwd123
      - MAXREG_PASSWORD=maxreg
      - BASE_LANG=en
      - ADMIN_EMAIL_ADDRESS=root@localhost
      - SMTP_SERVER_HOST_NAME=localhost
      - SKIN=iot18
      - UPDATE_APPS_ON_REBOOT=yes
      - KEEP_RUNNING=yes
    restart: on-failure
    networks:
      - maxnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure    
  maximo-ui:
    image: maximo/maxapps:latest
    ports:
      - 80:9080
    networks:
      - maxnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  maxnet:


